// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klsjwhmybgjhlcjwjset.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtsc2p3aG15YmdqaGxjandqc2V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTA4NjQsImV4cCI6MjA2MzkyNjg2NH0.sHJz16RnFnnkRIdT1h-Rs5gKXu9rd_-0ELKHDBHBFyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);